### ISSUE TITLE
Bruteforce common backdoors never finishes

### ISSUE THREAD

**Issue by tanaydin** [m4ll0k/WAScan#83]
Task done function missing in exceptions in backdoor scanner.

**Comment by m4ll0k** [comment]
I'm writing new version, thanks @tanaydin for your contributions

**Comment by S-Ch22** [comment]
In params.py, task_done() is including also the exceptions. Anyway, the problem still persists, not letting the program finish.
It seems it just happens when big quantity of items in the queue is involved.
I did a bit of debugging, and found out that the problem is related with a thread_lock.
I solved it not setting daemons and making they end work more cleanly. Now tried and works smoothly.
I can send u the debugging/code changes if it can be useful )
