### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by shadihh9** [m4ll0k/WAScan#86]
when i scan i see message [!] Error: ('The read operation timed out',)
and stop

**Comment by S-Ch22** [comment]
I was looking at the code, and it seems like it is due to this line in lib/request/request.py:

try:
	resp = urllib2.urlopen(req)
except urllib2.HTTPError,e:			
	resp = e
except socket.error,e:	
	exit(warn('Error: %s'%e))
except urllib2.URLError,e:		                                       
        exit(warn('Error: %s'%e))
return ResponseObject(resp)

When a socket or url error happens (for example, because of the internet connection going out), the program calls "exit", stopping the program.

For solving the situation, as for me was more important to keep the program going than losing 1 test, I just changed that lines, taking out the "exit" part:

except socket.error,e:
	warn('Error Socket: %s'%e)
.
.
